
["Enabled/Disabled Spells: (All are set to true by default)"]
	"Self Propulsion Enabled" = true
	"Force of Wind Enabled" = true
	"Strike From Above Enabled" = true
	"Everchanging Skies Enabled" = true
	"Dying Knowledge Enabled" = true
	"Linguist Enabled" = true
	"Airy Protection Enabled" = true
	"Lifebringer Enabled" = true
	"Beast Tamer Enabled" = true
	"Wild Aid Enabled" = true
	"Molding Lands Enabled" = true
	"Nurturing Roots Enabled" = true
	"Advantageous Growth Enabled" = true
	"Forest Affinity Enabled" = true
	"Mind Bender Enabled" = true
	"Ghostly Steed Enabled" = true
	"Withering Stench Enabled" = true
	"Dark Age Enabled" = true
	"Rotten Heart Enabled" = true
	"Nocturnal Enabled" = true
	"Coven's Rule Enabled" = true

["Costs and Cooldowns: (Cooldowns are in ticks)"]
	#DEFAULT = 8
	"Self Propulsion Cost" = 8
	#DEFAULT = 50
	"Self Propulsion Cooldown" = 50
	#DEFAULT = 10
	"Force of Wind Cost" = 10
	#DEFAULT = 70
	"Force of Wind Cooldown" = 70
	#DEFAULT = 40
	"Strike From Above Cost" = 40
	#DEFAULT = 200
	"Strike From Above Cooldown" = 200
	#DEFAULT = 70
	"Everchanging Skies Cost" = 70
	#DEFAULT = 600
	"Everchanging Skies Cooldown" = 600
	#DEFAULT = 25
	"Lifebringer Cost" = 25
	#DEFAULT = 80
	"Lifebringer Cooldown" = 80
	#DEFAULT = 60
	"Beast Tamer Cost" = 60
	#DEFAULT = 60
	"Beast Tamer Cooldown" = 60
	#DEFAULT = 20
	"Wild Aid Cost" = 20
	#DEFAULT = 80
	"Wild Aid Cooldown" = 80
	#DEFAULT = 55
	"Molding Lands Cost" = 55
	#DEFAULT = 35
	"Molding Lands Cooldown" = 35
	#DEFAULT = 30
	"Mind Bender Cost" = 30
	#DEFAULT = 50
	"Mind Bender Cooldown" = 50
	#DEFAULT = 35
	"Ghostly Steed Cost" = 35
	#DEFAULT = 200
	"Ghostly Steed Cooldown" = 200
	#DEFAULT = 20
	"Withering Stench Cost" = 20
	#DEFAULT = 35
	"Withering Stench Cooldown" = 35
	#DEFAULT = 70
	"Dark Age Cost" = 70
	#DEFAULT = 4000
	"Dark Age Cooldown" = 4000

["Droprates: (0 is never drop, 20 is always drop)"]
	#DEFAULT = 1
	"Archaic Heart Droprate" = 1
	#DEFAULT = 3
	"Beating Heart Droprate" = 1
	#DEFAULT = 8
	"Sweet Heart Droprate" = 1

